"""
RigBackend Protocol and BackendType enum.

All rig backend implementations (GQRXRigCtl, HamlibRigCtl) must satisfy the
RigBackend structural protocol.  BackendType is the shared discriminator used
by both RigEndpoint and ModeTranslator.

Frequency contract: all get_frequency / set_frequency values are int Hz.
Level contract:     get_level() returns int in units of dB × 10.
"""

from enum import Enum
from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from rig_remote.models.rig_endpoint import RigEndpoint


class BackendType(str, Enum):
    GQRX = "GQRX"
    HAMLIB = "HAMLIB"


@runtime_checkable
class RigBackend(Protocol):
    """Structural interface every rig backend must satisfy."""

    @property
    def endpoint(self) -> "RigEndpoint": ...

    @endpoint.setter
    def endpoint(self, value: "RigEndpoint") -> None: ...

    def set_frequency(self, frequency: int) -> None: ...
    def get_frequency(self) -> int: ...
    def set_mode(self, mode: str) -> None: ...
    def get_mode(self) -> str: ...
    def get_level(self) -> int: ...
    def set_vfo(self, vfo: str) -> str: ...
    def get_vfo(self) -> str: ...
    def start_recording(self) -> str: ...
    def stop_recording(self) -> str: ...
    def set_rit(self, rit: int) -> str: ...
    def get_rit(self) -> str: ...
    def set_xit(self, xit: int) -> str: ...
    def get_xit(self) -> str: ...
    def set_split_freq(self, split_freq: int) -> str: ...
    def get_split_freq(self) -> int: ...
    def set_split_mode(self, split_mode: str) -> str: ...
    def get_split_mode(self) -> str: ...
    def set_func(self, func: str) -> str: ...
    def get_func(self) -> str: ...
    def set_parm(self, parm: str) -> str: ...
    def get_parm(self) -> str: ...
    def set_antenna(self, antenna: int) -> str: ...
    def get_antenna(self) -> int: ...
    def rig_reset(self, reset_signal: str) -> str: ...
